visualization:
  connection:
    default:
      name: localhost
      url: http://localhost:8000
      rawxml: true
  network:
    # The time interval (milliseconds) to request the dataservice for new changes.
    interval: 10000
  calculation:
    # The time interval (milliseconds) to recalculate the position of the nodes.
    interval: 5000
    # Count of Iterations for the position calculation of the nodes.
    iterations: 100
  highlights:
    # Timeout (milliseconds) to show the highlights for new and deleted nodes.
    timeout: 5000
  node:
    translation:
      # The animation time for the translation of a node to the new position.
      duration: 3000
    information:
      # Sets the style for detailed node information when a node is selected
      # Possible values are:
      # XML_BREAKDOWN: breaks down the XML structure of nodes; the encapsulated XML
      #                of Extended Identifiers will be shown as a sub XML tree
      # PLAIN_XML:     a simple output of a nodes information, encapsulated XML
      #                will remain a single String
      style: XML_BREAKDOWN
  identifier:
    text:
      # Sets the text style for identifier nodes; possible values are:
      # SINGLE_LINE: a minimized style with all information in a single line
      # MULTI_LINE:  a more detailed style with possibly more information,
      #              using multiple lines
      # COMPACT:     a style that tries to use a single line, but will use
      #              additional lines when necessary and useful (for example
      #              for Extended Identifiers)
      style: COMPACT
      # If true, the prefix 'extended identifier: ' is shown before the actual name of an extended identifier.
      # This is not supported by all styles. 
      showextendedidentifierprefix: true
    node:
      # Sets the geometric style of identifier nodes; possible values are:
      # RECTANGLES_WITH_ROUNDED_CORNERS
      # RECTANGLES_WITH_SQUARE_CORNERS
      # ELLIPSE
      style: RECTANGLES_WITH_ROUNDED_CORNERS
  metadata:
    text:
      # Sets the text style for metadata nodes; possible values are:
      # SINGLE_LINE:    just the typename of the metadata is used
      # WITH_TIMESTAMP: adds a line with the publisher timestamp to the typename
      # COMPACT:        further information on additional lines
      style: COMPACT
    node:
      # Sets the geometric style of identifier nodes; possible values are:
      # RECTANGLES_WITH_ROUNDED_CORNERS
      # RECTANGLES_WITH_SQUARE_CORNERS
      # ELLIPSE
      style: RECTANGLES_WITH_SQUARE_CORNERS
  history:
    navigation:
      # Sets the control mechanism for history navigation; possible values are:
      # TAB_BASED_NAVIGATION:          uses multiple tabs to switch between
      #                                live view, history view and delta view
      # RANGE_SLIDER_BASED_NAVIGATION: uses a slider with two knobs that
      #                                includes all possible modes
      style: TAB_BASED_NAVIGATION
  searchandfilter:
    # Sets the search and filtering mechanism; possible values are:
    # SIMPLE_SEARCH_AND_NO_FILTER: a simple search functionality, using a single textfield
    #                              and matches every node containing the given 
    #                              input string
    style: SIMPLE_SEARCH_AND_NO_FILTER
    # value in 0.0 to 1.0 for transparency of elements that do not match a search value
    transparency : 0.2
      
dataservice:
  connectiontype: rest
  
guicontroller:
  zfactor: 0.03
  xyfactor: 20.0

window:
  width: 1280
  height: 720
  divider: 170
  position:
    x: 0
    y: 0

color:
  background: '0xFFFFFF'
  edge: '0x000000'
  metadata:
    text: '0x000000'
    inside: '0xFF9966'
    outside: '0xFF9966'
    border: '0x000000'
  node:
    new: '0x266E62'
    delete: '0xA73946'
    selected: '0xCEB100'
    search: '0x88A538'
  identifier:
    access-request:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    device:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    identity:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    ip-address:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    mac-address:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    extended:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
